from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOCAL_BIN_DIR = PROJECT_ROOT / ".local" / "bin"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "output" / "audio"
DEFAULT_TRANSCRIPT_DIR = PROJECT_ROOT / "output" / "transcripts"

WHISPER_MODEL_DEFAULT = "small"
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"

DEFAULT_CHUNK_MINUTES = 10.0
DEFAULT_MAX_WORKERS = 4
LONG_AUDIO_WARN_MINUTES = 30.0
STT_PROGRESS_SEGMENT_INTERVAL = 50

SAMPLE_RATE = 16_000
CHANNELS = 1
MP3_BITRATE = "96k"

WAV_CODEC = "pcm_s16le"
MP3_CODEC = "libmp3lame"

FFMPEG_STDERR_LOG_LIMIT = 2048
